import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.tsx"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/comment",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/highlight",
		"@codemirror/history",
		"@codemirror/lint",
		"@codemirror/matchbrackets",
		"@codemirror/panel",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/tooltip",
		"@codemirror/view",
		...builtinModules
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
});

function copyStaticFiles() {
	if (!fs.existsSync("dist")) {
		fs.mkdirSync("dist");
	}
	fs.copyFileSync("manifest.json", "dist/manifest.json");
	fs.copyFileSync("styles.css", "dist/styles.css");
	console.log("Copied manifest.json and styles.css to dist/");
}

if (prod) {
	await context.rebuild();
	copyStaticFiles();
	process.exit(0);
} else {
	copyStaticFiles();
	await context.watch();
}
